### PR TITLE
✨feat: create hero section

### PR DESCRIPTION
**Pull request by DinuAR**
## Summary

_Provide an overview..._
- _Update SCSS file_
- _Add hero image_
- _Create hero section UI_

## Details

Add photo credits to the hero image 

## References

- [Hero image reference link](https://unsplash.com/photos/ajE5goOGzZc)

## Checklist

- [x] Tested Changes
- [x] Stakeholder Approval
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No error nor warning in the console.
- [x] I joined a screenshot of the app before and after the fix.

### Before

hero section before

### After
hero section after

### After - mobile view
after mobile

## Test Environments
- _Windows 10 Pro_
- _VSCode_

### CODE REVIEW

**Review by DinuAR — COMMENTED** [review]
Self-reviewed by me. (@DinuAR)
@kesaralive @Naween-Pasindu @Nawoda-Jayasinghe

**Review by Nawoda-Jayasinghe — APPROVED** [review]
seems okay @DinuAR

**Review by kesaralive — APPROVED** [review]
This seems okay to me. @DinuAR

**Review by Naween-Pasindu — APPROVED** [review]
seems fine @DinuAR

**Pull request merged**
