### PR TITLE
✨feat: create list component

### PR DESCRIPTION
**Pull request by kesaralive**
## Summary

- 💄 create color config
- 💄 create transition mixins
- 💄 create component/list.scss
- ✨ update ListItem components

## Details

Improved UI & Updated Sass config files.

## References

- [Sass mixins](https://sass-lang.com/)

## Checklist

- [x] Tested Changes
- [x] Stakeholder Approval
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No error nor warning in the console.
- [x] I joined a screenshot of the app before and after the fix.

### Before
screenshot-localhost_3000-2022 01 20-21_43_00

### After
screenshot-localhost_3000-2022 01 20-21_41_52

### After - mobile
screenshot-localhost_3000-2022 01 20-21_44_02

## Test Environments
- _Windows 10 Pro_
- _VSCode_
## Other Notes

- color config created in the config.scss
- transition mixins added in config.scss

### CODE REVIEW

**Review by kesaralive — COMMENTED** [review]
self reviewed by @kesaralive

**Review by Naween-Pasindu — COMMENTED** [review]
Seems fine

**Review by Naween-Pasindu — APPROVED** [review]
Seems ok

**Review by Nawoda-Jayasinghe — APPROVED** [review]
seems fine @kesaralive

**Pull request merged**
